import { Question } from './types';
import { getQuestionsForMode, QUESTIONS } from './questions';
import { MODE_INFO, LIFE_AREAS } from './types';

interface ExportData {
  responses: Record<string, { value: string | string[] | Record<string, unknown> }>;
  mode: 'quick' | 'ok' | 'deep';
  year: number;
}

export function formatResponseValue(
  value: string | string[] | Record<string, unknown> | undefined,
  questionType: Question['type']
): string {
  if (!value) return '';

  if (typeof value === 'string') {
    return value;
  }

  if (Array.isArray(value)) {
    return value.filter(Boolean).join('\n');
  }

  if (typeof value === 'object') {
    if (questionType === 'rating') {
      return LIFE_AREAS
        .map(area => `${area.name}: ${(value as Record<string, number>)[area.id] || 0}/10`)
        .join('\n');
    }
    return Object.entries(value)
      .map(([k, v]) => `${k}: ${v}`)
      .join('\n');
  }

  return String(value);
}

export function generateCSV(data: ExportData): string {
  const questions = getQuestionsForMode(data.mode);
  const rows: string[][] = [
    ['LifeCompass Export', ''],
    [`Year: ${data.year}`, `Mode: ${MODE_INFO[data.mode].name}`],
    ['', ''],
    ['Question', 'Response'],
  ];

  questions.forEach((q) => {
    const response = data.responses[q.id];
    const value = formatResponseValue(response?.value, q.type);
    rows.push([q.title, value.replace(/\n/g, '; ')]);
  });

  return rows
    .map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(','))
    .join('\n');
}

export function downloadCSV(data: ExportData): void {
  const csvContent = generateCSV(data);
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `lifecompass-${data.year}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function downloadPDF(data: ExportData): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();
  const questions = getQuestionsForMode(data.mode);

  let y = 20;
  const lineHeight = 7;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const maxWidth = doc.internal.pageSize.width - 2 * margin;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(`LifeCompass ${data.year}`, margin, y);
  y += 15;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${MODE_INFO[data.mode].name} Mode Reflection`, margin, y);
  y += 20;

  // Line separator
  doc.setDrawColor(200);
  doc.line(margin, y, doc.internal.pageSize.width - margin, y);
  y += 15;

  let currentSection = '';

  questions.forEach((q) => {
    const response = data.responses[q.id];
    if (!response) return;

    // Section header
    if (q.section !== currentSection) {
      currentSection = q.section;

      if (y > pageHeight - 60) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(
        currentSection === 'past' ? 'Part One: Looking Back' : 'Part Two: Looking Forward',
        margin,
        y
      );
      y += 15;
    }

    // Check page break
    if (y > pageHeight - 50) {
      doc.addPage();
      y = 20;
    }

    // Question title
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(q.title, maxWidth);
    doc.text(titleLines, margin, y);
    y += titleLines.length * lineHeight + 3;

    // Response
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const responseText = formatResponseValue(response.value, q.type) || '(No response)';
    const responseLines = doc.splitTextToSize(responseText, maxWidth);

    if (y + responseLines.length * lineHeight > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }

    doc.text(responseLines, margin, y);
    y += responseLines.length * lineHeight + 12;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by LifeCompass | Page ${i} of ${pageCount}`,
      margin,
      pageHeight - 10
    );
  }

  doc.save(`lifecompass-${data.year}.pdf`);
}

// Generate shareable card data
export function generateShareCardData(
  type: 'word_of_year' | 'accomplishments' | 'gratitude' | 'dreams',
  responses: Record<string, { value: unknown }>,
  year: number
) {
  const content: Record<string, unknown> = { year };

  switch (type) {
    case 'word_of_year':
      content.word = responses['word_of_year']?.value || '';
      break;
    case 'accomplishments':
      content.items = responses['accomplishments']?.value || [];
      break;
    case 'gratitude':
      content.text = responses['gratitude']?.value || '';
      break;
    case 'dreams':
      content.items = responses['dreams']?.value || [];
      break;
  }

  return content;
}
